//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reusable_project_Form_.A_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A_ServiceReference.A_ServicesSoap")]
    public interface A_ServicesSoap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_theme", ReplyAction="*")]
        Reusable_project_Form_.A_ServiceReference.Create_themeResponse Create_theme(Reusable_project_Form_.A_ServiceReference.Create_themeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_theme", ReplyAction="*")]
        System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.Create_themeResponse> Create_themeAsync(Reusable_project_Form_.A_ServiceReference.Create_themeRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTheme", ReplyAction="*")]
        Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse UpdateTheme(Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTheme", ReplyAction="*")]
        System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse> UpdateThemeAsync(Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTheme", ReplyAction="*")]
        bool DeleteTheme(int Theme_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTheme", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteThemeAsync(int Theme_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignRefereeToProject", ReplyAction="*")]
        bool AssignRefereeToProject(int projectId, int refereeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignRefereeToProject", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AssignRefereeToProjectAsync(int projectId, int refereeId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_themeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_theme", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.A_ServiceReference.Create_themeRequestBody Body;
        
        public Create_themeRequest() {
        }
        
        public Create_themeRequest(Reusable_project_Form_.A_ServiceReference.Create_themeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_themeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Deadline;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float Budget;
        
        public Create_themeRequestBody() {
        }
        
        public Create_themeRequestBody(string Name, string Duration, System.DateTime Deadline, float Budget) {
            this.Name = Name;
            this.Duration = Duration;
            this.Deadline = Deadline;
            this.Budget = Budget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Create_themeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create_themeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.A_ServiceReference.Create_themeResponseBody Body;
        
        public Create_themeResponse() {
        }
        
        public Create_themeResponse(Reusable_project_Form_.A_ServiceReference.Create_themeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Create_themeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Create_themeResult;
        
        public Create_themeResponseBody() {
        }
        
        public Create_themeResponseBody(bool Create_themeResult) {
            this.Create_themeResult = Create_themeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateThemeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTheme", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.A_ServiceReference.UpdateThemeRequestBody Body;
        
        public UpdateThemeRequest() {
        }
        
        public UpdateThemeRequest(Reusable_project_Form_.A_ServiceReference.UpdateThemeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateThemeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Theme_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Deadline;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float Budget;
        
        public UpdateThemeRequestBody() {
        }
        
        public UpdateThemeRequestBody(int Theme_ID, string Name, string Duration, System.DateTime Deadline, float Budget) {
            this.Theme_ID = Theme_ID;
            this.Name = Name;
            this.Duration = Duration;
            this.Deadline = Deadline;
            this.Budget = Budget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateThemeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateThemeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.A_ServiceReference.UpdateThemeResponseBody Body;
        
        public UpdateThemeResponse() {
        }
        
        public UpdateThemeResponse(Reusable_project_Form_.A_ServiceReference.UpdateThemeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateThemeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateThemeResult;
        
        public UpdateThemeResponseBody() {
        }
        
        public UpdateThemeResponseBody(bool UpdateThemeResult) {
            this.UpdateThemeResult = UpdateThemeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface A_ServicesSoapChannel : Reusable_project_Form_.A_ServiceReference.A_ServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class A_ServicesSoapClient : System.ServiceModel.ClientBase<Reusable_project_Form_.A_ServiceReference.A_ServicesSoap>, Reusable_project_Form_.A_ServiceReference.A_ServicesSoap {
        
        public A_ServicesSoapClient() {
        }
        
        public A_ServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public A_ServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A_ServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A_ServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reusable_project_Form_.A_ServiceReference.Create_themeResponse Reusable_project_Form_.A_ServiceReference.A_ServicesSoap.Create_theme(Reusable_project_Form_.A_ServiceReference.Create_themeRequest request) {
            return base.Channel.Create_theme(request);
        }
        
        public bool Create_theme(string Name, string Duration, System.DateTime Deadline, float Budget) {
            Reusable_project_Form_.A_ServiceReference.Create_themeRequest inValue = new Reusable_project_Form_.A_ServiceReference.Create_themeRequest();
            inValue.Body = new Reusable_project_Form_.A_ServiceReference.Create_themeRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Duration = Duration;
            inValue.Body.Deadline = Deadline;
            inValue.Body.Budget = Budget;
            Reusable_project_Form_.A_ServiceReference.Create_themeResponse retVal = ((Reusable_project_Form_.A_ServiceReference.A_ServicesSoap)(this)).Create_theme(inValue);
            return retVal.Body.Create_themeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.Create_themeResponse> Reusable_project_Form_.A_ServiceReference.A_ServicesSoap.Create_themeAsync(Reusable_project_Form_.A_ServiceReference.Create_themeRequest request) {
            return base.Channel.Create_themeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.Create_themeResponse> Create_themeAsync(string Name, string Duration, System.DateTime Deadline, float Budget) {
            Reusable_project_Form_.A_ServiceReference.Create_themeRequest inValue = new Reusable_project_Form_.A_ServiceReference.Create_themeRequest();
            inValue.Body = new Reusable_project_Form_.A_ServiceReference.Create_themeRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Duration = Duration;
            inValue.Body.Deadline = Deadline;
            inValue.Body.Budget = Budget;
            return ((Reusable_project_Form_.A_ServiceReference.A_ServicesSoap)(this)).Create_themeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse Reusable_project_Form_.A_ServiceReference.A_ServicesSoap.UpdateTheme(Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest request) {
            return base.Channel.UpdateTheme(request);
        }
        
        public bool UpdateTheme(int Theme_ID, string Name, string Duration, System.DateTime Deadline, float Budget) {
            Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest inValue = new Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest();
            inValue.Body = new Reusable_project_Form_.A_ServiceReference.UpdateThemeRequestBody();
            inValue.Body.Theme_ID = Theme_ID;
            inValue.Body.Name = Name;
            inValue.Body.Duration = Duration;
            inValue.Body.Deadline = Deadline;
            inValue.Body.Budget = Budget;
            Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse retVal = ((Reusable_project_Form_.A_ServiceReference.A_ServicesSoap)(this)).UpdateTheme(inValue);
            return retVal.Body.UpdateThemeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse> Reusable_project_Form_.A_ServiceReference.A_ServicesSoap.UpdateThemeAsync(Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest request) {
            return base.Channel.UpdateThemeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reusable_project_Form_.A_ServiceReference.UpdateThemeResponse> UpdateThemeAsync(int Theme_ID, string Name, string Duration, System.DateTime Deadline, float Budget) {
            Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest inValue = new Reusable_project_Form_.A_ServiceReference.UpdateThemeRequest();
            inValue.Body = new Reusable_project_Form_.A_ServiceReference.UpdateThemeRequestBody();
            inValue.Body.Theme_ID = Theme_ID;
            inValue.Body.Name = Name;
            inValue.Body.Duration = Duration;
            inValue.Body.Deadline = Deadline;
            inValue.Body.Budget = Budget;
            return ((Reusable_project_Form_.A_ServiceReference.A_ServicesSoap)(this)).UpdateThemeAsync(inValue);
        }
        
        public bool DeleteTheme(int Theme_ID) {
            return base.Channel.DeleteTheme(Theme_ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteThemeAsync(int Theme_ID) {
            return base.Channel.DeleteThemeAsync(Theme_ID);
        }
        
        public bool AssignRefereeToProject(int projectId, int refereeId) {
            return base.Channel.AssignRefereeToProject(projectId, refereeId);
        }
        
        public System.Threading.Tasks.Task<bool> AssignRefereeToProjectAsync(int projectId, int refereeId) {
            return base.Channel.AssignRefereeToProjectAsync(projectId, refereeId);
        }
    }
}
