//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reusable_project_Form_.R_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="R_ServiceReference.R_ServiceSoap")]
    public interface R_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        Reusable_project_Form_.R_ServiceReference.CreateAccountResponse CreateAccount(Reusable_project_Form_.R_ServiceReference.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Reusable_project_Form_.R_ServiceReference.CreateAccountResponse> CreateAccountAsync(Reusable_project_Form_.R_ServiceReference.CreateAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.R_ServiceReference.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(Reusable_project_Form_.R_ServiceReference.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(string username, string password, string email) {
            this.username = username;
            this.password = password;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Reusable_project_Form_.R_ServiceReference.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(Reusable_project_Form_.R_ServiceReference.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAccountResult;
        
        public CreateAccountResponseBody() {
        }
        
        public CreateAccountResponseBody(bool CreateAccountResult) {
            this.CreateAccountResult = CreateAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface R_ServiceSoapChannel : Reusable_project_Form_.R_ServiceReference.R_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class R_ServiceSoapClient : System.ServiceModel.ClientBase<Reusable_project_Form_.R_ServiceReference.R_ServiceSoap>, Reusable_project_Form_.R_ServiceReference.R_ServiceSoap {
        
        public R_ServiceSoapClient() {
        }
        
        public R_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public R_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public R_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public R_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reusable_project_Form_.R_ServiceReference.CreateAccountResponse Reusable_project_Form_.R_ServiceReference.R_ServiceSoap.CreateAccount(Reusable_project_Form_.R_ServiceReference.CreateAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public bool CreateAccount(string username, string password, string email) {
            Reusable_project_Form_.R_ServiceReference.CreateAccountRequest inValue = new Reusable_project_Form_.R_ServiceReference.CreateAccountRequest();
            inValue.Body = new Reusable_project_Form_.R_ServiceReference.CreateAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            Reusable_project_Form_.R_ServiceReference.CreateAccountResponse retVal = ((Reusable_project_Form_.R_ServiceReference.R_ServiceSoap)(this)).CreateAccount(inValue);
            return retVal.Body.CreateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reusable_project_Form_.R_ServiceReference.CreateAccountResponse> Reusable_project_Form_.R_ServiceReference.R_ServiceSoap.CreateAccountAsync(Reusable_project_Form_.R_ServiceReference.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reusable_project_Form_.R_ServiceReference.CreateAccountResponse> CreateAccountAsync(string username, string password, string email) {
            Reusable_project_Form_.R_ServiceReference.CreateAccountRequest inValue = new Reusable_project_Form_.R_ServiceReference.CreateAccountRequest();
            inValue.Body = new Reusable_project_Form_.R_ServiceReference.CreateAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            return ((Reusable_project_Form_.R_ServiceReference.R_ServiceSoap)(this)).CreateAccountAsync(inValue);
        }
    }
}
